# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - webapp-laszlo-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Extract Git hash
        run: git rev-parse HEAD > git_hash.txt

      - name: Install dependencies
        run: |
          uv venv
          uv export --format requirements-txt --no-hashes --output-file requirements.txt
          uv pip install -r requirements.txt
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'webapp-laszlo-test'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FE83027C5CF54FDC91A9638B45741353 }}